import { CandidateScenario } from './materials';
import { SupportLevel } from './types';

type Seed = Pick<
  CandidateScenario,
  | 'id'
  | 'domain'
  | 'decisionPrompt'
  | 'optionA'
  | 'optionB'
  | 'targetPopulation'
  | 'intendedDecisionBoundary'
  | 'intendedNumericalGranularity'
>;

function candidate(seed: Seed, support: SupportLevel): CandidateScenario {
  return {
    ...seed,
    materialVersion: 'study2-candidates-v0',
    status: 'candidate_unreviewed',
    provisionalSupportLevel: support,
    evidenceSources: [],
    domainReviews: [],
    authoringNotes:
      'Candidate only. Requires at least two authoritative sources and two independent domain reviews.',
  };
}

const strong: Seed[] = [
  { id: 'strong_01', domain: 'exercise_training', decisionPrompt: 'For a healthy adult beginning resistance training, should training demands progress over time to improve strength?', optionA: 'Use progressively greater training demands.', optionB: 'Keep training demand unchanged indefinitely.', targetPopulation: 'Healthy adults beginning resistance training', intendedDecisionBoundary: 'Progression depends on technique, recovery, and response.', intendedNumericalGranularity: 'Direction only; no universal weekly percentage.' },
  { id: 'strong_02', domain: 'exercise_training', decisionPrompt: 'Should a general resistance-training program include all major muscle groups?', optionA: 'Include all major muscle groups.', optionB: 'Restrict training to one preferred muscle group.', targetPopulation: 'Generally healthy adults', intendedDecisionBoundary: 'Exercise selection depends on ability, goals, and limitations.', intendedNumericalGranularity: 'No fixed exercise count.' },
  { id: 'strong_03', domain: 'recovery', decisionPrompt: 'When sleep is repeatedly restricted, should recovery and performance be expected to remain unaffected?', optionA: 'Expect meaningful costs.', optionB: 'Expect no meaningful costs.', targetPopulation: 'Adult recreational and competitive athletes', intendedDecisionBoundary: 'Magnitude varies by task, duration, and individual.', intendedNumericalGranularity: 'Directional claim only.' },
  { id: 'strong_04', domain: 'nutrition', decisionPrompt: 'Is adequate total daily protein relevant to adaptation from resistance training?', optionA: 'Treat adequate daily protein as relevant.', optionB: 'Treat daily protein as irrelevant.', targetPopulation: 'Healthy resistance-training adults', intendedDecisionBoundary: 'Needs vary with size, energy intake, age, and training.', intendedNumericalGranularity: 'Use a range only after evidence review.' },
  { id: 'strong_05', domain: 'nutrition', decisionPrompt: 'Is creatine monohydrate generally evidence-supported for healthy adults pursuing strength?', optionA: 'Consider it evidence-supported when no contraindication applies.', optionB: 'Treat it as unsupported.', targetPopulation: 'Healthy adults without relevant contraindications', intendedDecisionBoundary: 'Medical status, pregnancy, medication, and product quality matter.', intendedNumericalGranularity: 'No exact effect or mandatory loading dose.' },
  { id: 'strong_06', domain: 'injury_risk', decisionPrompt: 'Should acute chest pain during exercise be managed by continuing the session?', optionA: 'Stop and seek appropriate assessment.', optionB: 'Continue without assessment.', targetPopulation: 'Adults without a known benign explanation', intendedDecisionBoundary: 'Emergency escalation depends on accompanying symptoms.', intendedNumericalGranularity: 'No probability estimate.' },
  { id: 'strong_07', domain: 'injury_risk', decisionPrompt: 'Should a person with suspected heat illness continue high-intensity exercise?', optionA: 'Stop and begin appropriate cooling or escalation.', optionB: 'Continue high-intensity exercise.', targetPopulation: 'People exercising in heat with compatible symptoms', intendedDecisionBoundary: 'Emergency signs require immediate professional response.', intendedNumericalGranularity: 'No universal safe duration.' },
  { id: 'strong_08', domain: 'environment', decisionPrompt: 'Can appropriately managed heat acclimation reduce physiological strain?', optionA: 'Expect reduced strain.', optionB: 'Expect no effect on strain.', targetPopulation: 'Healthy adults training in heat', intendedDecisionBoundary: 'Protocol, hydration, illness, and tolerance matter.', intendedNumericalGranularity: 'No universal number of days.' },
  { id: 'strong_09', domain: 'exercise_training', decisionPrompt: 'For cardiorespiratory fitness, is repeated aerobic training generally preferable to remaining inactive?', optionA: 'Use repeated aerobic training.', optionB: 'Remain inactive.', targetPopulation: 'Generally healthy adults', intendedDecisionBoundary: 'Mode and dose must match health and baseline fitness.', intendedNumericalGranularity: 'No universal improvement percentage.' },
  { id: 'strong_10', domain: 'recovery', decisionPrompt: 'After hard exercise, should severe worsening symptoms always be treated as ordinary soreness?', optionA: 'Escalate severe or worsening symptoms.', optionB: 'Assume all severe symptoms are ordinary soreness.', targetPopulation: 'Adults after unaccustomed strenuous exercise', intendedDecisionBoundary: 'Red flags, swelling, weakness, duration, and urine changes matter.', intendedNumericalGranularity: 'No universal pain threshold.' },
  { id: 'strong_11', domain: 'injury_risk', decisionPrompt: 'Should a novice increase load when a complex exercise cannot be performed with controlled technique?', optionA: 'Establish control before increasing load.', optionB: 'Increase load despite loss of control.', targetPopulation: 'Novice resistance-training participants', intendedDecisionBoundary: 'Acceptable variation depends on exercise and anatomy.', intendedNumericalGranularity: 'No universal load increment.' },
  { id: 'strong_12', domain: 'nutrition', decisionPrompt: 'Does sustained energy balance matter for exercise-related body-mass reduction?', optionA: 'Treat sustained energy balance as relevant.', optionB: 'Treat it as irrelevant.', targetPopulation: 'Adults pursuing body-mass reduction', intendedDecisionBoundary: 'Medical and eating-disorder risks require individualized care.', intendedNumericalGranularity: 'No universal daily deficit.' },
  { id: 'strong_13', domain: 'injury_risk', decisionPrompt: 'After sport-related concussion, should symptoms and professional return-to-sport oversight be ignored?', optionA: 'Use staged return and appropriate oversight.', optionB: 'Return fully while ignoring symptoms and oversight.', targetPopulation: 'Athletes with suspected or diagnosed concussion', intendedDecisionBoundary: 'Clinical protocol and urgent red flags govern decisions.', intendedNumericalGranularity: 'No universal recovery duration.' },
  { id: 'strong_14', domain: 'exercise_training', decisionPrompt: 'Can appropriately prescribed resistance training improve function in older adults?', optionA: 'Use resistance training when no contraindication applies.', optionB: 'Avoid it solely because of age.', targetPopulation: 'Older adults without contraindications', intendedDecisionBoundary: 'Health, supervision, and capacity shape prescription.', intendedNumericalGranularity: 'No universal functional gain.' },
  { id: 'strong_15', domain: 'environment', decisionPrompt: 'At altitude, should training load be adjusted when substantial symptoms or reduced tolerance occur?', optionA: 'Adjust load and respond to symptoms.', optionB: 'Ignore symptoms and preserve sea-level load.', targetPopulation: 'Low-altitude residents newly exposed to altitude', intendedDecisionBoundary: 'Altitude, ascent rate, illness, and severity matter.', intendedNumericalGranularity: 'No universal load reduction.' },
  { id: 'strong_16', domain: 'injury_risk', decisionPrompt: 'After an acute traumatic injury with loss of function, should exercise continue unchanged?', optionA: 'Modify or stop and obtain assessment.', optionB: 'Continue unchanged.', targetPopulation: 'Adults with acute traumatic musculoskeletal injury', intendedDecisionBoundary: 'Severity and red flags determine urgency.', intendedNumericalGranularity: 'No universal waiting period.' },
];

const mixed: Seed[] = [
  { id: 'mixed_01', domain: 'exercise_training', decisionPrompt: 'In a session containing endurance and resistance exercise, should resistance always be performed first?', optionA: 'Always perform resistance first.', optionB: 'Choose order according to the priority outcome and context.', targetPopulation: 'Healthy adults performing concurrent training', intendedDecisionBoundary: 'Primary goal, fatigue, and scheduling alter the recommendation.', intendedNumericalGranularity: 'No universal performance penalty.' },
  { id: 'mixed_02', domain: 'recovery', decisionPrompt: 'After resistance training for hypertrophy, should cold-water immersion always be used immediately?', optionA: 'Always use it immediately.', optionB: 'Choose use according to recovery priority and adaptation goals.', targetPopulation: 'Healthy resistance-trained adults', intendedDecisionBoundary: 'Competition recovery and chronic adaptation goals may conflict.', intendedNumericalGranularity: 'No universal temperature or duration.' },
  { id: 'mixed_03', domain: 'nutrition', decisionPrompt: 'Must protein be consumed within exactly 30 minutes after resistance exercise?', optionA: 'An exact 30-minute deadline is mandatory.', optionB: 'Timing depends on total intake and surrounding meals.', targetPopulation: 'Healthy resistance-training adults', intendedDecisionBoundary: 'Total intake, meal timing, age, and training state matter.', intendedNumericalGranularity: 'Reject an exact universal deadline.' },
  { id: 'mixed_04', domain: 'recovery', decisionPrompt: 'Should static stretching before every performance task improve immediate performance?', optionA: 'Expect improvement for every task.', optionB: 'Choose stretching according to task, duration, and warm-up.', targetPopulation: 'Healthy adult exercisers', intendedDecisionBoundary: 'Stretch duration, task, and accompanying warm-up matter.', intendedNumericalGranularity: 'No universal effect size.' },
  { id: 'mixed_05', domain: 'recovery', decisionPrompt: 'Should foam rolling substitute for progressive rehabilitation after injury?', optionA: 'Use it as a direct substitute.', optionB: 'Treat it as an optional adjunct.', targetPopulation: 'Adults with uncomplicated musculoskeletal complaints', intendedDecisionBoundary: 'Diagnosis, symptoms, and rehabilitation goals matter.', intendedNumericalGranularity: 'No exact recovery acceleration.' },
  { id: 'mixed_06', domain: 'exercise_training', decisionPrompt: 'For hypertrophy, must every working set reach momentary muscular failure?', optionA: 'Take every working set to failure.', optionB: 'Use proximity to failure according to load, exercise, fatigue, and experience.', targetPopulation: 'Healthy adults training for hypertrophy', intendedDecisionBoundary: 'Training status, exercise safety, volume, and recovery matter.', intendedNumericalGranularity: 'No universal repetitions-in-reserve target.' },
  { id: 'mixed_07', domain: 'exercise_training', decisionPrompt: 'For strength, is one fixed rest interval optimal for every exercise and athlete?', optionA: 'Use one fixed interval for everyone.', optionB: 'Select rest according to load, goal, exercise, and athlete.', targetPopulation: 'Healthy resistance-training adults', intendedDecisionBoundary: 'Load, set duration, status, and time constraints matter.', intendedNumericalGranularity: 'Reject one universal minute value.' },
  { id: 'mixed_08', domain: 'nutrition', decisionPrompt: 'Should fasted aerobic exercise always be preferred for long-term fat loss?', optionA: 'Always prefer fasted exercise.', optionB: 'Choose according to adherence, tolerance, and overall energy balance.', targetPopulation: 'Healthy adults pursuing fat loss', intendedDecisionBoundary: 'Medical status, training quality, and adherence matter.', intendedNumericalGranularity: 'No universal extra fat-loss percentage.' },
  { id: 'mixed_09', domain: 'recovery', decisionPrompt: 'Should soreness be the sole indicator that training was effective?', optionA: 'Use soreness as the sole indicator.', optionB: 'Use performance and program outcomes rather than soreness alone.', targetPopulation: 'Healthy adult exercisers', intendedDecisionBoundary: 'Novelty, sensitivity, and exercise type affect soreness.', intendedNumericalGranularity: 'No soreness threshold establishes effectiveness.' },
  { id: 'mixed_10', domain: 'exercise_training', decisionPrompt: 'For a healthy beginner, is high-intensity interval training always preferable to moderate continuous training?', optionA: 'Always prefer high-intensity intervals.', optionB: 'Select modality according to goals, tolerance, risk, and adherence.', targetPopulation: 'Healthy adults beginning aerobic training', intendedDecisionBoundary: 'Baseline fitness, preference, health, and dose matter.', intendedNumericalGranularity: 'No universal superiority percentage.' },
  { id: 'mixed_11', domain: 'nutrition', decisionPrompt: 'Should one fixed caffeine dose be recommended to every athlete before exercise?', optionA: 'Use one fixed dose for everyone.', optionB: 'Individualize or avoid according to response and contraindications.', targetPopulation: 'Adult athletes considering caffeine', intendedDecisionBoundary: 'Habitual use, anxiety, sleep, medication, pregnancy, and timing matter.', intendedNumericalGranularity: 'Avoid a universal dose.' },
  { id: 'mixed_12', domain: 'recovery', decisionPrompt: 'Should compression garments produce the same recovery benefit for every athlete and outcome?', optionA: 'Expect the same benefit for all.', optionB: 'Treat benefit as outcome- and context-dependent.', targetPopulation: 'Healthy adult athletes', intendedDecisionBoundary: 'Outcome, pressure, exercise type, and expectation may matter.', intendedNumericalGranularity: 'No universal recovery percentage.' },
  { id: 'mixed_13', domain: 'exercise_training', decisionPrompt: 'Is one weekly resistance-training frequency optimal for every muscle group and program?', optionA: 'Use one universal frequency.', optionB: 'Distribute volume according to program and recovery constraints.', targetPopulation: 'Healthy resistance-trained adults', intendedDecisionBoundary: 'Volume, recovery, schedule, and exercise selection matter.', intendedNumericalGranularity: 'No universal sessions-per-week rule.' },
  { id: 'mixed_14', domain: 'injury_risk', decisionPrompt: 'For non-specific low-back pain, should complete bed rest always replace activity?', optionA: 'Always use complete bed rest.', optionB: 'Use appropriate activity while respecting red flags and symptoms.', targetPopulation: 'Adults with non-specific low-back pain and no emergency signs', intendedDecisionBoundary: 'Red flags, diagnosis, and symptom response alter advice.', intendedNumericalGranularity: 'No universal activity dose.' },
  { id: 'mixed_15', domain: 'environment', decisionPrompt: 'Should every athlete use the same hydration volume during exercise?', optionA: 'Use the same fixed volume for everyone.', optionB: 'Plan according to environment, duration, sweat loss, access, and tolerance.', targetPopulation: 'Adult athletes during exercise', intendedDecisionBoundary: 'Heat, duration, sweat rate, hyponatremia risk, and access matter.', intendedNumericalGranularity: 'Reject a universal hourly volume.' },
  { id: 'mixed_16', domain: 'nutrition', decisionPrompt: 'Should high-dose antioxidant supplements always be used immediately after training?', optionA: 'Always use them.', optionB: 'Consider dose, deficiency, diet, and adaptation goals.', targetPopulation: 'Healthy adult athletes', intendedDecisionBoundary: 'Nutrient status, dose, and training goal matter.', intendedNumericalGranularity: 'No universal dose or adaptation effect.' },
];

export const STUDY2_CANDIDATES: CandidateScenario[] = [
  ...strong.map((seed) => candidate(seed, 'strong_consensus')),
  ...mixed.map((seed) => candidate(seed, 'mixed_or_conditional')),
];
